name: Publish
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: paralenz/actions/setup-node@1.2.1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
      - run: yarn lint
      - run: yarn test
      - run: yarn build
      - run: yarn publish
