name: Publish
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: paralenz/actions/setup-node@v1.3.0
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
      - run: yarn lint
      - run: yarn test
      - run: yarn build
      - run: yarn publish
