name: Pull Request
on:  
  pull_request:
    types: [opened, synchronize, edited]
jobs:
  title:
    name: Ensure that title uses gitmoji
    runs-on: ubuntu-latest
    steps:
      - uses: paralenz/actions/gitmoji@v1.3.0

  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: paralenz/actions/setup-node@v1.3.0
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v3
      - uses: paralenz/actions/setup-node@v1.3.0
      - name: Run linting
        run: yarn lint

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v3
      - uses: paralenz/actions/setup-node@v1.3.0
      - name: Run tests
        run: yarn test